/** Generated by the default template from graphql-java-generator */
package org.allGraphQLCases.server;

import com.graphql_java_generator.GraphQLField;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;
import java.util.List;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("MyQueryType")
public class MyQueryType  {

	public MyQueryType(){
		// No action
	}

	@GraphQLNonScalar(fieldName = "withoutParameters", graphQLTypeName = "Character", javaClass = Character.class)
	List<Character> withoutParameters;


	@GraphQLNonScalar(fieldName = "withOneOptionalParam", graphQLTypeName = "Character", javaClass = Character.class)
	Character withOneOptionalParam;


	@GraphQLNonScalar(fieldName = "withOneMandatoryParam", graphQLTypeName = "Character", javaClass = Character.class)
	Character withOneMandatoryParam;


	@GraphQLNonScalar(fieldName = "withEnum", graphQLTypeName = "Character", javaClass = Character.class)
	Character withEnum;


	@GraphQLNonScalar(fieldName = "withList", graphQLTypeName = "Character", javaClass = Character.class)
	List<Character> withList;


	@GraphQLNonScalar(fieldName = "allFieldCases", graphQLTypeName = "AllFieldCases", javaClass = AllFieldCases.class)
	AllFieldCases allFieldCases;


	@GraphQLNonScalar(fieldName = "error", graphQLTypeName = "Character", javaClass = Character.class)
	Character error;


	@GraphQLNonScalar(fieldName = "aBreak", graphQLTypeName = "break", javaClass = _break.class)
	_break aBreak;


	@GraphQLScalar(fieldName = "directiveOnQuery", graphQLTypeName = "String", javaClass = String.class)
	List<String> directiveOnQuery;


	@GraphQLNonScalar(fieldName = "directiveOnField", graphQLTypeName = "Character", javaClass = Character.class)
	Character directiveOnField;



	public void setWithoutParameters(List<Character> withoutParameters) {
		this.withoutParameters = withoutParameters;
	}

	public List<Character> getWithoutParameters() {
		return withoutParameters;
	}

	public void setWithOneOptionalParam(Character withOneOptionalParam) {
		this.withOneOptionalParam = withOneOptionalParam;
	}

	public Character getWithOneOptionalParam() {
		return withOneOptionalParam;
	}

	public void setWithOneMandatoryParam(Character withOneMandatoryParam) {
		this.withOneMandatoryParam = withOneMandatoryParam;
	}

	public Character getWithOneMandatoryParam() {
		return withOneMandatoryParam;
	}

	public void setWithEnum(Character withEnum) {
		this.withEnum = withEnum;
	}

	public Character getWithEnum() {
		return withEnum;
	}

	public void setWithList(List<Character> withList) {
		this.withList = withList;
	}

	public List<Character> getWithList() {
		return withList;
	}

	public void setAllFieldCases(AllFieldCases allFieldCases) {
		this.allFieldCases = allFieldCases;
	}

	public AllFieldCases getAllFieldCases() {
		return allFieldCases;
	}

	public void setError(Character error) {
		this.error = error;
	}

	public Character getError() {
		return error;
	}

	public void setABreak(_break aBreak) {
		this.aBreak = aBreak;
	}

	public _break getABreak() {
		return aBreak;
	}

	public void setDirectiveOnQuery(List<String> directiveOnQuery) {
		this.directiveOnQuery = directiveOnQuery;
	}

	public List<String> getDirectiveOnQuery() {
		return directiveOnQuery;
	}

	public void setDirectiveOnField(Character directiveOnField) {
		this.directiveOnField = directiveOnField;
	}

	public Character getDirectiveOnField() {
		return directiveOnField;
	}

    public String toString() {
        return "MyQueryType {"
				+ "withoutParameters: " + withoutParameters
				+ ", "
				+ "withOneOptionalParam: " + withOneOptionalParam
				+ ", "
				+ "withOneMandatoryParam: " + withOneMandatoryParam
				+ ", "
				+ "withEnum: " + withEnum
				+ ", "
				+ "withList: " + withList
				+ ", "
				+ "allFieldCases: " + allFieldCases
				+ ", "
				+ "error: " + error
				+ ", "
				+ "aBreak: " + aBreak
				+ ", "
				+ "directiveOnQuery: " + directiveOnQuery
				+ ", "
				+ "directiveOnField: " + directiveOnField
        		+ "}";
    }

    /**
	 * Enum of field names
	 */
	 public static enum Field implements GraphQLField {
		WithoutParameters("withoutParameters"),
		WithOneOptionalParam("withOneOptionalParam"),
		WithOneMandatoryParam("withOneMandatoryParam"),
		WithEnum("withEnum"),
		WithList("withList"),
		AllFieldCases("allFieldCases"),
		Error("error"),
		ABreak("aBreak"),
		DirectiveOnQuery("directiveOnQuery"),
		DirectiveOnField("directiveOnField");

		private String fieldName;

		Field(String fieldName) {
			this.fieldName = fieldName;
		}

		public String getFieldName() {
			return fieldName;
		}

		public Class<?> getGraphQLType() {
			return this.getClass().getDeclaringClass();
		}

	}

	public static Builder builder() {
			return new Builder();
		}



	/**
	 * Builder
	 */
	public static class Builder {
		private List<Character> withoutParameters;
		private Character withOneOptionalParam;
		private Character withOneMandatoryParam;
		private Character withEnum;
		private List<Character> withList;
		private AllFieldCases allFieldCases;
		private Character error;
		private _break aBreak;
		private List<String> directiveOnQuery;
		private Character directiveOnField;


		public Builder withWithoutParameters(List<Character> withoutParameters) {
			this.withoutParameters = withoutParameters;
			return this;
		}
		public Builder withWithOneOptionalParam(Character withOneOptionalParam) {
			this.withOneOptionalParam = withOneOptionalParam;
			return this;
		}
		public Builder withWithOneMandatoryParam(Character withOneMandatoryParam) {
			this.withOneMandatoryParam = withOneMandatoryParam;
			return this;
		}
		public Builder withWithEnum(Character withEnum) {
			this.withEnum = withEnum;
			return this;
		}
		public Builder withWithList(List<Character> withList) {
			this.withList = withList;
			return this;
		}
		public Builder withAllFieldCases(AllFieldCases allFieldCases) {
			this.allFieldCases = allFieldCases;
			return this;
		}
		public Builder withError(Character error) {
			this.error = error;
			return this;
		}
		public Builder withABreak(_break aBreak) {
			this.aBreak = aBreak;
			return this;
		}
		public Builder withDirectiveOnQuery(List<String> directiveOnQuery) {
			this.directiveOnQuery = directiveOnQuery;
			return this;
		}
		public Builder withDirectiveOnField(Character directiveOnField) {
			this.directiveOnField = directiveOnField;
			return this;
		}

		public MyQueryType build() {
			MyQueryType _object = new MyQueryType();
			_object.setWithoutParameters(withoutParameters);
			_object.setWithOneOptionalParam(withOneOptionalParam);
			_object.setWithOneMandatoryParam(withOneMandatoryParam);
			_object.setWithEnum(withEnum);
			_object.setWithList(withList);
			_object.setAllFieldCases(allFieldCases);
			_object.setError(error);
			_object.setABreak(aBreak);
			_object.setDirectiveOnQuery(directiveOnQuery);
			_object.setDirectiveOnField(directiveOnField);
			return _object;
		}
	}
}
